### PR TITLE
fix: blocks in white - invisible with white background

### LINKED ISSUE #12: The HTML version renders code blocks in white - invisible with white background.
The pandoc.css contains styles to renders ``embedded code text`` white (line 125???). This is invisible on white backgrounds, ex:

gswl_book_html

Need to update the CSS.

### PR DESCRIPTION
**Pull request by deild**
Fixes #12

### CODE REVIEW

**Comment by rolfschr** [comment]
Hi,

thank you very much for your contribution. I'd add your name to the list of contributors but wasn't able to figure it out. Let me know if you want to add it.

I saw that you made several other changes in your fork. Do you intend to get them upstream, too?

**Comment by deild** [comment]
you can add Samuel Marcaille :-)

When I would be satisfied with the modification I think I will propose the change. 
I am mainly preparing a translation into French.

**Comment by rolfschr** [comment]
Okay, Thanks anyway.

**Comment by rolfschr** [comment]
Maybe we can internationalize the book? I wouldn't have the time now but end of summer/automn I could work on making i18n (i.e. make the necessary changes so that english is just one of many languages). You could then merge in all you french translations? Just a quick idea. What do you think?

**Pull request merged**
