### PR TITLE
corrected typos ecoystem -> ecosystem

### PR DESCRIPTION
**Pull request by KSonny4**
Hi! corrected typo and will help more if I found anything else.

Sincerely,

Petr Kubelka

### CODE REVIEW

**Comment by rolfschr** [comment]
Hi,

thank you very much for your help! Do you want to have your name in the list of contributors (see end of the book). If so, please add it in this pull request (names are sorted alphabetically). Otherwise, I'll simply merge.

**Comment by KSonny4** [comment]
Ok, why not! My name is Petr Kubelka

**Comment by rolfschr** [comment]
Could you please add your name to ``09-end/01.md`` ?

**Comment by KSonny4** [comment]
Done.

**Pull request merged**
